//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web07.GD.NPTINH.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web07.GD.NPTINH.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ đã tồn tại trong hệ thống vui lòng kiểm tra lại..
        /// </summary>
        public static string Error_UserMessages_DuplicateCode {
            get {
                return ResourceManager.GetString("Error_UserMessages_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA!.
        /// </summary>
        public static string Error_UserMessages_Exception {
            get {
                return ResourceManager.GetString("Error_UserMessages_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string Error_UserMessages_Invalid {
            get {
                return ResourceManager.GetString("Error_UserMessages_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e001.
        /// </summary>
        public static string ErrorCode_Exception {
            get {
                return ResourceManager.GetString("ErrorCode_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e008.
        /// </summary>
        public static string ErrorCode_InValidDate {
            get {
                return ResourceManager.GetString("ErrorCode_InValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e006.
        /// </summary>
        public static string ErrorCode_InValidEmail {
            get {
                return ResourceManager.GetString("ErrorCode_InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e007.
        /// </summary>
        public static string ErrorCode_InValidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorCode_InValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e005.
        /// </summary>
        public static string ErrorCode_RequiredFullName {
            get {
                return ResourceManager.GetString("ErrorCode_RequiredFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e004.
        /// </summary>
        public static string ErrorCode_RequiredTeacherCode {
            get {
                return ResourceManager.GetString("ErrorCode_RequiredTeacherCode", resourceCulture);
            }
        }
    }
}
